"""KHQR codes (02_TECHNICAL.md section 10.3).

The expected strings were generated by NBC's own JavaScript SDK
(`bakong-khqr` 1.0.20, `generateIndividual`) with the same inputs and its
clock fixed at 1790900000000 ms, so these pin the format to the official
one. The SDK also refuses riel amounts with cents.
"""

from datetime import UTC, datetime
from decimal import Decimal

import pytest

from app.models import Currency
from app.services.khqr import crc16, individual_khqr
from tests.helpers import KHQR, add_product, place_order, registered_seller, set_payments, track

NOW = datetime.fromtimestamp(1_790_900_000, UTC)


@pytest.mark.parametrize(
    ("account", "name", "currency", "amount", "bill", "expected"),
    [
        (
            "dara@aclb",
            "SOK DARA",
            Currency.USD,
            "12.50",
            "1001",
            "00020101021229130009dara@aclb520459995303840540512.505802KH5908SOK DARA"
            "6010Phnom Penh6208010410019934001317909000000000113179098640000063048609",
        ),
        (
            "dara@aclb",
            "SOK DARA",
            Currency.USD,
            "12.00",
            "1002",
            "00020101021229130009dara@aclb5204599953038405402125802KH5908SOK DARA"
            "6010Phnom Penh620801041002993400131790900000000011317909864000006304DCD0",
        ),
        (
            "sokha_shop@abaa",
            "Sokha Shop",
            Currency.KHR,
            "45000.00",
            "1003",
            "00020101021229190015sokha_shop@abaa5204599953031165405450005802KH5910Sokha Shop"
            "6010Phnom Penh6208010410039934001317909000000000113179098640000063042D1C",
        ),
    ],
)
def test_matches_the_official_sdk(account, name, currency, amount, bill, expected):
    code = individual_khqr(
        bakong_account_id=account,
        merchant_name=name,
        currency=currency,
        amount=Decimal(amount),
        bill_number=bill,
        now=NOW,
    )
    assert code == expected


@pytest.mark.parametrize(
    ("currency", "amount"),
    [(Currency.KHR, "1500.50"), (Currency.USD, "0.00"), (Currency.KHR, "0.00")],
)
def test_no_code_for_amounts_khqr_cannot_carry(currency, amount):
    code = individual_khqr(
        bakong_account_id="dara@aclb",
        merchant_name="SOK DARA",
        currency=currency,
        amount=Decimal(amount),
        bill_number="1001",
        now=NOW,
    )
    assert code is None


def test_crc16_is_ccitt_false():
    assert crc16("123456789") == "29B1"  # the standard check value


async def test_a_khqr_order_page_carries_a_code_for_its_total(client, auth_headers):
    headers, store_id, slug = await registered_seller(client, auth_headers)
    await set_payments(client, headers, khqr=KHQR)
    cap = await add_product(store_id, "cap", stock=5)

    placed = await place_order(client, slug, [(cap, None, 2)], total="20.00", payment_method="khqr")

    khqr = placed.json()["payment"]["khqr"]
    assert khqr["merchant_name"] == "SOK DARA"
    code = khqr["code"]
    assert "0009dara@aclb" in code
    assert "5303840" in code and "540220" in code  # USD 20
    assert "0105#1001" in code  # the order number
    assert code[-4:] == crc16(code[:-4])
    tracked = (await track(client, slug, placed.json()["id"])).json()
    assert tracked["payment"]["khqr"]["merchant_name"] == "SOK DARA"


async def test_no_code_once_the_seller_turns_khqr_off(client, auth_headers):
    headers, store_id, slug = await registered_seller(client, auth_headers)
    await set_payments(client, headers, khqr=KHQR)
    cap = await add_product(store_id, "cap", stock=5)
    placed = await place_order(client, slug, [(cap, None, 1)], total="10.00", payment_method="khqr")

    await set_payments(client, headers, khqr={**KHQR, "enabled": False})

    tracked = (await track(client, slug, placed.json()["id"])).json()
    assert (tracked["payment"]["method"], tracked["payment"]["khqr"]) == ("khqr", None)
