"""seller phone login

Sellers log in with a phone number checked in Telegram (founder's choice
2026-10-09), so seller.phone becomes unique, and email optional (new
accounts have none).

Phones typed before were free text: they're rewritten in one form. A
number that can't be read, or that an older account already has, is
cleared: that account keeps logging in by email. Only the founder's test
shops existed (2026-10-09).

Revision ID: 005c6870a409
Revises: 5b3201ea7f7d
Create Date: 2026-10-09 10:41:45.802407

"""

import re
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005c6870a409"
down_revision: str | Sequence[str] | None = "5b3201ea7f7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _normalize(raw: str) -> str | None:
    """app/services/phone.py's normalize_phone as of this migration
    (copied: a migration mustn't change when the app's code does)."""
    phone = re.sub(r"[\s\-().]", "", raw)
    if phone.startswith("00"):
        phone = "+" + phone[2:]
    for prefix in ("+855", "855"):
        if phone.startswith(prefix):
            phone = "0" + phone[len(prefix) :].lstrip("0")
            break
    if re.fullmatch(r"0[1-9]\d{7,8}", phone) or re.fullmatch(r"\+[1-9]\d{7,14}", phone):
        return phone
    return None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("seller", "phone", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("seller", "email", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
    conn = op.get_bind()
    seen: set[str] = set()
    rows = conn.execute(sa.text("SELECT id, phone FROM seller ORDER BY created_at, id"))
    for seller_id, raw in rows.all():
        phone = _normalize(raw or "")
        if phone in seen:
            phone = None
        if phone is not None:
            seen.add(phone)
        conn.execute(
            sa.text("UPDATE seller SET phone = :phone WHERE id = :id"),
            {"phone": phone, "id": seller_id},
        )
    op.create_unique_constraint(op.f("uq_seller_phone"), "seller", ["phone"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_seller_phone"), "seller", type_="unique")
    # Accounts made with a phone have no email: give them one that can't
    # be anyone's (.invalid is reserved), so they can be found again.
    op.execute("UPDATE seller SET email = id::text || '@phone.invalid' WHERE email IS NULL")
    op.execute("UPDATE seller SET phone = '' WHERE phone IS NULL")
    op.alter_column("seller", "email", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("seller", "phone", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
