"""store contact phone and messenger

Revision ID: 007ae4403215
Revises: 5ee23aad5482
Create Date: 2026-10-08 15:06:16.278367

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007ae4403215"
down_revision: str | Sequence[str] | None = "5ee23aad5482"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("store", sa.Column("contact_phone", sa.Text(), nullable=True))
    op.add_column("store", sa.Column("messenger_username", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store", "messenger_username")
    op.drop_column("store", "contact_phone")
    # ### end Alembic commands ###
