"""seller login facebook tiktok

"Continue with Facebook" and "Continue with TikTok" (founder's choice
2026-10-09): two more providers, and the name the provider gave (TikTok
gives no email), shown in Settings.

Revision ID: 39a133fd8c02
Revises: 4520c66e86de
Create Date: 2026-10-09 15:53:27.429334

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39a133fd8c02"
down_revision: str | Sequence[str] | None = "4520c66e86de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seller_login", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_seller_login_login_provider"), "seller_login", type_="check")
    op.create_check_constraint(
        op.f("ck_seller_login_login_provider"),
        "seller_login",
        "provider IN ('google', 'facebook', 'tiktok')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM seller_login WHERE provider <> 'google'")
    op.drop_constraint(op.f("ck_seller_login_login_provider"), "seller_login", type_="check")
    op.create_check_constraint(
        op.f("ck_seller_login_login_provider"), "seller_login", "provider IN ('google')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller_login", "name")
    # ### end Alembic commands ###
