"""seller login google

"Continue with Google" (founder's choice 2026-10-09): seller_login ties a
Google account (later Facebook, TikTok) to a seller, and a seller made
with Google has no password until they add one. No app_user grant: not
tenant data.

Revision ID: 4520c66e86de
Revises: 005c6870a409
Create Date: 2026-10-09 13:50:05.725798

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4520c66e86de"
down_revision: str | Sequence[str] | None = "005c6870a409"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seller_login",
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "google",
                name="login_provider",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('google')", name=op.f("ck_seller_login_login_provider")),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
            name=op.f("fk_seller_login_seller_id_seller"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_login")),
        sa.UniqueConstraint("provider", "provider_user_id", name=op.f("uq_seller_login_provider")),
        sa.UniqueConstraint("seller_id", "provider", name=op.f("uq_seller_login_seller_id")),
    )
    op.alter_column("seller", "password_hash", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("seller", "password_hash", existing_type=sa.TEXT(), nullable=False)
    op.drop_table("seller_login")
    # ### end Alembic commands ###
