"""store low stock alert

Revision ID: 49da40196f18
Revises: 007ae4403215
Create Date: 2026-10-08 15:28:58.598314

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49da40196f18"
down_revision: str | Sequence[str] | None = "007ae4403215"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store", sa.Column("low_stock_alert", sa.Integer(), server_default="5", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store", "low_stock_alert")
    # ### end Alembic commands ###
