"""phone check

Revision ID: 5b3201ea7f7d
Revises: ae070e4b3006
Create Date: 2026-10-09 10:31:17.670416

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b3201ea7f7d"
down_revision: str | Sequence[str] | None = "ae070e4b3006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_check",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_check")),
        sa.UniqueConstraint("code", name=op.f("uq_phone_check_code")),
    )
    op.create_index(
        op.f("ix_phone_check_telegram_user_id"), "phone_check", ["telegram_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phone_check_telegram_user_id"), table_name="phone_check")
    op.drop_table("phone_check")
    # ### end Alembic commands ###
