"""store orders paused

Revision ID: 5ee23aad5482
Revises: 883276fadeed
Create Date: 2026-10-08 14:45:50.002362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ee23aad5482"
down_revision: str | Sequence[str] | None = "883276fadeed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store", sa.Column("orders_paused", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("store", sa.Column("orders_resume_on", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store", "orders_resume_on")
    op.drop_column("store", "orders_paused")
    # ### end Alembic commands ###
