"""seller role and staff store

Revision ID: ae070e4b3006
Revises: 49da40196f18
Create Date: 2026-10-08 16:11:45.890489

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae070e4b3006"
down_revision: str | Sequence[str] | None = "49da40196f18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seller",
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "staff",
                name="seller_role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="owner",
            nullable=False,
        ),
    )
    op.add_column("seller", sa.Column("store_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_seller_store_id"), "seller", ["store_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_seller_store_id_store"),
        "seller",
        "store",
        ["store_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###
    # Not picked up by autogenerate (the role's own CHECK comes with the column).
    op.create_check_constraint(
        op.f("ck_seller_staff_has_store"), "seller", "(role = 'staff') = (store_id IS NOT NULL)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_seller_staff_has_store"), "seller", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_seller_store_id_store"), "seller", type_="foreignkey")
    op.drop_index(op.f("ix_seller_store_id"), table_name="seller")
    op.drop_column("seller", "store_id")
    op.drop_column("seller", "role")
    # ### end Alembic commands ###
